version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_client
      - build_player
      - test_ubuntu_18_04:
          requires:
            - build_client
            - build_player
      - test_windows:
          requires:
            - build_client
            - build_player
      - store_artifacts:
          requires:
            - test_ubuntu_18_04
            - test_windows

jobs:
  build_client:
    docker:
      - image: circleci/golang:1.12.9

    steps:
      - checkout

      - restore_cache:
          key: go-mod-v1-{{ checksum "client/go.sum" }}

      - run:
          name: Build Alda client executable
          command: client/bin/build

      - save_cache:
          key: go-mod-v1-{{ checksum "client/go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Move build to output directory
          working_directory: client/target
          command: |
            mkdir build
            cp -R $(../../bin/current-content-sha client) build/client

      - persist_to_workspace:
          root: client/target
          paths:
            - build

  build_player:
    docker:
      - image: daveyarwood/alda-player:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "player/build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Build Alda player executable
          command: player/bin/build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "player/build.gradle.kts" }}

      - run:
          name: Move build to output directory
          working_directory: player/target
          command: |
            mkdir -p build
            cp -R $(../../bin/current-content-sha player) build/player

      - persist_to_workspace:
          root: player/target
          paths:
            - build

  test_ubuntu_18_04:
    docker:
      - image: circleci/openjdk:8

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Install alda and alda-player
          working_directory: /tmp/workspace/build
          command: |
            mkdir -p /home/circleci/bin
            cp client/linux-amd64/alda /home/circleci/bin/
            cp player/non-windows/alda-player /home/circleci/bin/
            chmod +x /home/circleci/bin/alda
            chmod +x /home/circleci/bin/alda-player
            alda version
            alda-player info

      - run: alda -v doctor --no-audio

  test_windows:
    executor: win/default

    steps:
      - attach_workspace:
          at: C:\Users\circleci\alda

      - run:
          name: Install alda and alda-player
          working_directory: C:\Users\circleci\alda\build
          command: |
            New-Item -ItemType "directory" -Path "C:\Program Files\Alda\bin"
            Copy-Item -Path "client\windows-amd64\alda.exe" -Destination "C:\Program Files\Alda\bin"
            Copy-Item -Path "player\windows\alda-player.exe" -Destination "C:\Program Files\Alda\bin"
            alda version
            alda-player info

      - run: alda -v doctor --no-audio

  store_artifacts:
    docker:
      - image: circleci/buildpack-deps:bionic

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - store_artifacts:
          path: /tmp/workspace/build/client
          destination: client

      - store_artifacts:
          path: /tmp/workspace/build/player
          destination: player
