version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_client
      - build_player
      - test_ubuntu_18_04:
          requires:
            - build_client
            - build_player
      - test_macos:
          requires:
            - build_client
            - build_player
      - test_windows:
          requires:
            - build_client
            - build_player
      - store_artifacts:
          filters:
            branches:
              only: v2
          requires:
            - test_ubuntu_18_04
            - test_macos
            - test_windows

jobs:
  build_client:
    docker:
      - image: circleci/golang:1.12.9

    steps:
      - checkout

      - restore_cache:
          key: go-mod-v1-{{ checksum "client/go.sum" }}

      - run:
          name: Build Alda client executable
          command: client/bin/build

      - save_cache:
          key: go-mod-v1-{{ checksum "client/go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Move build to output directory
          working_directory: client/target
          command: |
            mkdir build
            cp -R $(../../bin/current-content-sha client) build/client

      - persist_to_workspace:
          root: client/target
          paths:
            - build

  build_player:
    docker:
      - image: daveyarwood/alda-player:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "player/build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Copy VERSION file because symlinks don't seem to work here
          command: |
            rm player/src/main/resources/VERSION
            cp VERSION player/src/main/resources/VERSION

      - run:
          name: Build Alda player executable
          command: player/bin/build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "player/build.gradle.kts" }}

      - run:
          name: Move build to output directory
          working_directory: player/target
          command: |
            mkdir -p build
            cp -R $(../../bin/current-content-sha player) build/player

      - persist_to_workspace:
          root: player/target
          paths:
            - build

  test_ubuntu_18_04:
    docker:
      - image: circleci/openjdk:8

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Install alda and alda-player
          working_directory: /tmp/workspace/build
          command: |
            mkdir -p /home/circleci/bin
            cp client/linux-amd64/alda /home/circleci/bin/
            cp player/non-windows/alda-player /home/circleci/bin/
            chmod +x /home/circleci/bin/alda
            chmod +x /home/circleci/bin/alda-player
            alda version
            alda-player info

      - run:
          name: alda doctor
          command: alda -v3 doctor --no-audio

      - run:
          name: "Troubleshooting: player logs"
          command: cat /home/circleci/.cache/alda/logs/alda-player.log
          when: on_fail

  test_macos:
    macos:
      xcode: 11.3.0

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Install alda and alda-player
          working_directory: /tmp/workspace/build
          command: |
            mkdir -p /usr/local/bin
            cp client/darwin-amd64/alda /usr/local/bin/
            cp player/non-windows/alda-player /usr/local/bin/
            chmod +x /usr/local/bin/alda
            chmod +x /usr/local/bin/alda-player
            alda version
            alda-player info

      - run:
          name: alda doctor
          command: alda -v3 doctor --no-audio

      - run:
          name: "Troubleshooting: player logs"
          command: cat /Users/distiller/Library/Caches/alda/logs/alda-player.log
          when: on_fail

  test_windows:
    executor: win/default

    steps:
      - attach_workspace:
          at: C:\Users\circleci\alda

      - run:
          name: Install alda and alda-player
          working_directory: C:\Users\circleci\alda\build
          command: |
            New-Item -ItemType "directory" -Path "C:\Program Files\Alda\bin"
            Copy-Item -Path "client\windows-amd64\alda.exe" -Destination "C:\Program Files\Alda\bin"
            Copy-Item -Path "player\windows\alda-player.exe" -Destination "C:\Program Files\Alda\bin"
            $env:PATH = "$env:PATH;C:\Program Files\Alda\bin"
            alda version
            alda-player info
            # Work around a bug in CircleCI Windows builds where it apparently
            # hangs forever if there are any background processes, e.g. the
            # player processes that `alda` spawns.
            Stop-Process -Name "alda-player"
            Stop-Process -Name "java"

      - run:
          name: alda doctor
          command: |
            $env:PATH = "$env:PATH;C:\Program Files\Alda\bin"
            alda -v3 doctor --no-audio
            # Work around a bug in CircleCI Windows builds where it apparently
            # hangs forever if there are any background processes, e.g. the
            # player processes that `alda` spawns.
            Stop-Process -Name "alda-player"
            Stop-Process -Name "java"

      - run:
          name: "Troubleshooting: player logs"
          command: type C:\Users\circleci\AppData\Local\alda\cache\logs\alda-player.log
          when: on_fail

  store_artifacts:
    docker:
      - image: circleci/buildpack-deps:bionic

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - store_artifacts:
          path: /tmp/workspace/build/client
          destination: client

      - store_artifacts:
          path: /tmp/workspace/build/player
          destination: player
